---
title: "Spiral of Silence"
author: "Patrick Halbach, André Calero Valdez"
date: "12 Dezember 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Hmisc)
library(tidyr)
library(tidyverse)
library(haven)
library(sjlabelled)
library(psych)
library(data.table)
library(hcictools)
library(summarytools)
```

First we clean our SPSS output files. For this purpose we remove identifying information..
```{r data-cleaning}
raw <- read_sav("data/SpiralofSilence.sav")

# filter incomplete responses  
raw[,c(-1:-10)] %>% filter((`filter_$`) > 0) -> data

data
# factors and ordinal data
data$Age <- as.numeric(data$Age)
data$Gender <- as.factor(data$Gender)

# calculate factors and scales

data <- data %>% mutate_if(~ any(is.na(.x)),~ if_else(is.na(.x),0,as.numeric(.x)))
data <- data %>% mutate_at(vars(starts_with("top")), as.factor)
```


GGPlot for Social Media Usage
```{r plot-smuse}

SMdata <- data[,c(3:8)]

### Sum the data using apply & use this for beautiful barplot
sumdata <- data.frame(value=apply(SMdata,2,sum))
sumdata$key <- c("Facebook", "Twitter", "Instagram","Google Plus","Snapchat","Youtube")

SMPlot <- ggplot(data=sumdata, aes(x=reorder(key, -value), y=value, fill=reorder(key, -value))) +
  geom_bar(stat="identity") +
  geom_text(aes(x=key,y=value, label=value),vjust=-1) +
  xlab("Social media service") +
  ylab("User count") +
  ylim(0,160) +
  scale_fill_viridis_d() +
  theme_grey()

SMPlot + guides(fill=FALSE)

ggsave("SocialMediaUse.pdf",width = 7, height = 4)

```


Plotting the initial/final opinion
```{r plot-initopinion}

rwthcolors <- hcictools::rwth.colorpalette()
agreement_palette <- colorRampPalette(c(rwthcolors$green,"white",rwthcolors$red))

# Building a dataframe from initial and final opinion variables
data %>% 
  select(toilet = ToiletsOpFinal, food = FoodOpFinal, ronaldo = RonaldoOpFinal, smoke = SmokedetOpFinal) %>% 
  add_rownames("id") %>% 
  gather(variable, value, -id) %>% 
  rename (final = value) -> final_data

data %>% 
  select(toilet = topToilets_opinion, food = topFood_opinion, ronaldo = topRonaldo_opinion, smoke =topSmokedet_opinion) %>% 
  add_rownames("id") %>% 
  gather(variable, value, -id) %>% 
  rename(initial = value) -> pre_data

# Joining the dataframes for creating the plot
pre_data %>% left_join(final_data) %>% 
  gather(state , value, -variable, -id) %>% 
  mutate(variable = factor(variable, levels=c("toilet","food","ronaldo","smoke"), 
                           labels = c("Paying usage fees \nfor public toilets", "Higher taxation of \nunhealthy food", 
                                      "Sympathy for football\nplayer Ronaldo", "Obligatory installation\nof smoke detectors") ), 
         state=factor(state, levels=c("initial", "final")), value=factor(value, levels=c("2","1"), labels = c("Approval", "Refusal"))) %>%
  group_by(state,variable, value) %>% 
  summarise(opinion = n()) %>% 
  ggplot() + 
  aes(x = state, y = opinion, fill = value) + 
  geom_bar(stat = "identity") + 
  facet_wrap(~variable, nrow=1) +
  geom_text(aes(label = scales::percent(opinion/163)), position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values=agreement_palette(2)) +
  labs(x="Topics and state", y="Opinion distribution") +
  theme_grey() +
  guides(fill=guide_legend(title = "Opinion"))

ggsave("Opinionchange.pdf",width = 7, height = 4)

```


Plotting the opinion change directions
```{r plot-opchangedirection}

rwthcolors <- hcictools::rwth.colorpalette()
agreement_palette2 <- colorRampPalette(c(rwthcolors$red,"white",rwthcolors$green))

# Building a dataframe from initial and final opinion variables
data %>% 
  select(toilet = ToiletsOpChange, food = FoodOpChange, ronaldo = RonaldoOpChange, smoke = SmokedetOpChange) %>% 
  add_rownames("id") %>% 
  gather(variable, value, -id) %>% 
  rename (direction = value, topic = variable) %>%
  subset(direction != 0) %>% 
  mutate(topic = factor(topic, levels=c("toilet","food","ronaldo","smoke"), 
                           labels = c("Paying usage fees \nfor public toilets", "Higher taxation of \nunhealthy food", 
                                      "Sympathy for football\nplayer Ronaldo", "Obligatory installation\nof smoke detectors") ),
    direction = factor(direction, levels=c("1", "2"), labels=c("From approval\nto rejection","From rejection\nto approval"))) %>% 
  arrange(topic, direction) %>% 
  ggplot() +
  aes(x=fct_rev(topic), fill=direction, order= -as.numeric(direction)) +
  geom_bar() +
  geom_text(aes(label=..count..),stat="count",position=position_stack(0.5)) +
  scale_fill_manual(values=agreement_palette2(2)) +
  scale_color_discrete("2", "1") +
  labs(x="Topics", y="Total opinion changers") +
  coord_flip() + 
  guides(fill = guide_legend(title="Direction of\nopinion change",reverse = TRUE)) +
  NULL



ggsave("OpinionchangeDirection.pdf",width = 7, height = 4)

```


Plotting Mean Comparisons
```{r plot-further}
variable_set <- c(
            "FB_schon_gehört",
            "FB_glaube_existiert",
            "FB_interessante_Beiträge",
            "FB_betrifft_persönlich",
            "FB_Problem",
            "FB_bewusstes_Vorgehen"
            )

label_set <- c(
              "sg",
              "existier",
              "interessant",
              "Betrifft per",
              "problem",
              "bewusst"
              )

make_variable_labels <- function(x) {
  factor(x, levels = variable_set,
            labels = label_set
            )
}

data %>% 
  dplyr::select(variable_set) %>% 
  map_df(as.numeric) %>% 
  psych::describe() %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  mutate (variablename = make_variable_labels(rowname)) -> plot_data
```